'''
Created on Mar 31, 2016


The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

     1: 1
     3: 1,3
     6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?

@author: Anders
'''

def factors(a):
    f = 0;
    for x in range(1,int(a/2)+1):
        if a%x==0:
            f+=1;
    return f+1;

sum=0;
for i in range(1,1000000):
    sum+=i;
    if sum%2==0 and sum%3==0 and sum%7==0 and sum%5==0 and sum%13==0 and sum%17==0:
        r = factors(sum)
        print(sum," ",r," ",i)
    else:
        r = 2;   
    if r>=500:
        print(i)
        break